exclude: '((ext-libs/)|(tests/)|(plugin/ui/qt/))$'
repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      args: ["-l", "120", "-v", "plugin"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        args: ["-rc", "plugin"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9  # pick a git hash / tag to point to
    hooks:
    -   id: flake8